apiVersion: promoter.argoproj.io/v1alpha1
kind: PromotionStrategy
metadata:
  annotations:
  name: argocon-demo
  namespace: default
spec:
  activeCommitStatuses:
  - key: argocd-health
  proposedCommitStatuses:
    - key: yaml-lint
  environments:
  - branch: environments/development
  - branch: environments/staging
    activeCommitStatuses:
      - key: performance-test
  - branch: environments/production
    proposedCommitStatuses:
    - key: deployment-freeze
  gitRepositoryRef:
    name: argocon-demo
