apiVersion: promoter.argoproj.io/v1alpha1
kind: CommitStatus
metadata:
  labels:
    promoter.argoproj.io/commit-status: deployment-freeze
  name: production-use2-freeze
  namespace: default
spec:
  description: Deployment Freeze Production
  gitRepositoryRef:
    name: argocon-demo
  name: environments/production-use2/deployment-freeze
  phase: pending
  sha: db79f0abd1156364014217f168fe3586bd217748
  url: https://example.com
