apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: integration-staging
  namespace: argocd
  labels:
    app: demo
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  sourceHydrator:
    drySource:
      path: user-configuration/staging/integration
      repoURL: https://github.com/zachaller/argocon-gitops-promoter-hydrate-demo.git
      targetRevision: manual-commit-status-talk
    hydrateTo:
      targetBranch: environments/staging-next
    syncSource:
      path: integration
      targetBranch: environments/staging
  syncPolicy:
    automated: {}
